# What is PyTorch?

## Tensors

In [1]:
from __future__ import print_function
import torch

In [4]:
# Construct a 5*3 empty matrix
x = torch.empty(5,3)
print(x)

tensor([[4.6837e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0653e-38, 1.0469e-38],
        [9.5510e-39, 8.7245e-39, 1.0653e-38]])


In [5]:
# Construct a randomly initialized matrix
x = torch.rand(5,3)
x

tensor([[0.1212, 0.3755, 0.3322],
        [0.7060, 0.5193, 0.0431],
        [0.0606, 0.3160, 0.7398],
        [0.6948, 0.3543, 0.5683],
        [0.3030, 0.1150, 0.4799]])

In [6]:
# Construct a zero matrix, and set the data type to long
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
# Construct a common tensor
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [8]:
# Construct a tensor, then construct another tensor based on the former tensor
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [9]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 1.1382, -0.6949,  0.0343],
        [ 1.3558,  0.1729, -0.7050],
        [ 0.3986,  0.3228,  0.0535],
        [-0.8004,  0.4166, -0.1620],
        [-0.3442, -0.6268, -0.1522]])

In [10]:
# Get the size of a tensor
x.size()

torch.Size([5, 3])

## Operations

### Add: Way 1

In [11]:
y = torch.rand(5, 3)
x + y

tensor([[ 1.1813, -0.1887,  0.4171],
        [ 2.2018,  0.6006,  0.2889],
        [ 0.6426,  0.6922,  0.0883],
        [-0.7869,  0.4413, -0.0678],
        [ 0.5683,  0.2711,  0.6906]])

### Add: Way 2

In [12]:
torch.add(x, y)

tensor([[ 1.1813, -0.1887,  0.4171],
        [ 2.2018,  0.6006,  0.2889],
        [ 0.6426,  0.6922,  0.0883],
        [-0.7869,  0.4413, -0.0678],
        [ 0.5683,  0.2711,  0.6906]])

### Add: Use an output tensor to store the result

In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 1.1813, -0.1887,  0.4171],
        [ 2.2018,  0.6006,  0.2889],
        [ 0.6426,  0.6922,  0.0883],
        [-0.7869,  0.4413, -0.0678],
        [ 0.5683,  0.2711,  0.6906]])

### Add: In-place

In [14]:
# Add x to y
y.add_(x)
y

tensor([[ 1.1813, -0.1887,  0.4171],
        [ 2.2018,  0.6006,  0.2889],
        [ 0.6426,  0.6922,  0.0883],
        [-0.7869,  0.4413, -0.0678],
        [ 0.5683,  0.2711,  0.6906]])

Note that any operation which would change the tensor has a prefix, such as `x.copy_(y)`, `x.t_()`, which will change `x`.

In [15]:
x.copy_(y)
x

tensor([[ 1.1813, -0.1887,  0.4171],
        [ 2.2018,  0.6006,  0.2889],
        [ 0.6426,  0.6922,  0.0883],
        [-0.7869,  0.4413, -0.0678],
        [ 0.5683,  0.2711,  0.6906]])

In [18]:
x.t_()
x

tensor([[ 1.1813,  2.2018,  0.6426, -0.7869,  0.5683],
        [-0.1887,  0.6006,  0.6922,  0.4413,  0.2711],
        [ 0.4171,  0.2889,  0.0883, -0.0678,  0.6906]])

### Index operation as in Numpy

In [20]:
x[:, 1:4]

tensor([[ 2.2018,  0.6426, -0.7869],
        [ 0.6006,  0.6922,  0.4413],
        [ 0.2889,  0.0883, -0.0678]])

#### Change a tensor's size or shape: `.view()`

In [21]:
x = torch.rand(4, 4)
x

tensor([[0.9089, 0.0648, 0.6228, 0.7501],
        [0.0364, 0.5997, 0.4292, 0.1779],
        [0.9810, 0.7894, 0.3001, 0.7633],
        [0.6820, 0.0088, 0.3186, 0.9039]])

In [22]:
y = x.view(16)
y

tensor([0.9089, 0.0648, 0.6228, 0.7501, 0.0364, 0.5997, 0.4292, 0.1779, 0.9810,
        0.7894, 0.3001, 0.7633, 0.6820, 0.0088, 0.3186, 0.9039])

In [23]:
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
z

tensor([[0.9089, 0.0648, 0.6228, 0.7501, 0.0364, 0.5997, 0.4292, 0.1779],
        [0.9810, 0.7894, 0.3001, 0.7633, 0.6820, 0.0088, 0.3186, 0.9039]])

In [24]:
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

#### Use `.item()` to get a (one-element-) tensor's value

In [25]:
x = torch.rand(1)
x

tensor([0.8069])

In [26]:
x.item()

0.8069329261779785